[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
artrade_pfp = "dMtyD9gkB41frDGEp4YuTmtv6fzdsjib3PGv7YhrVSM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=b7461f58-c0f8-40a9-a175-23649477fbd5"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
